### ISSUE TITLE
Soft error on compile

### ISSUE THREAD

**Issue by AndyTaylorTweet** [juribeparada/NXDN2DMR#1]
Soft error on compile;

`g++ -g -O3 -Wall -std=c++0x -pthread -c -o NXDN2DMR.o NXDN2DMR.cpp
NXDN2DMR.cpp: In member function ‘unsigned int CNXDN2DMR::truncID(unsigned int)’:
NXDN2DMR.cpp:750:31: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
  snprintf(temp, 8, "%0.7d", id);
                               ^
NXDN2DMR.cpp:750:31: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
g++ -g -O3 -Wall -std=c++0x -pthread -c -o NXDNNetwork.o NXDNNetwork.cpp`

**Comment by juribeparada** [comment]
It should be fixed now

**Comment by AndyTaylorTweet** [comment]
fixed - thank you.
Can you confirm if these new gateways have the same fixes as YSF2DMR for commented config files? I may well need that in the new ones too to help me being these services to Pi-Star.

**Comment by juribeparada** [comment]
Yes Andy, all new conversion softwares will remove quotes in config files.
